import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import AppProviders from '@/providers/app-providers';

import '@mantine/core/styles.css';
import { ColorSchemeScript, MantineProvider } from '@mantine/core';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <ColorSchemeScript />
      </head>

      <body className={inter.className}>
        <MantineProvider>
          <AppProviders>{children}</AppProviders>
        </MantineProvider>
      </body>
    </html>
  );
};

export default RootLayout;
